version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
<<<<<<< HEAD
      - image: circleci/node:10.16.0
=======
      - image: circleci/node:8.11
>>>>>>> 2f9e41111e9c0e2c0cfda490c32632b0c455c0e3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
<<<<<<< HEAD
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
=======
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
>>>>>>> 2f9e41111e9c0e2c0cfda490c32632b0c455c0e3

      - run: yarn install

      - save_cache:
<<<<<<< HEAD
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests! ppp, yarn 
      - run: yarn test
=======
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
>>>>>>> 2f9e41111e9c0e2c0cfda490c32632b0c455c0e3

    deploy:
      docker:
        - image: circleci/node:8.11
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
    workflows:
      version: 2
      build-deploy:
        jobs:
          - build
<<<<<<< HEAD
          - deploy:
              requires:
                - build
              filters:
              branches:
                  only: main
=======
          filters:
          branches:
            only: main
>>>>>>> 2f9e41111e9c0e2c0cfda490c32632b0c455c0e3
